[package]
name = "GraphQL"
version = "15.5.0"
author = "Roblox"
authors = [
	"Chris Trze≈õniewski <k.trzesniewski@gmail.com>",
	"Ignacio Falk <flakolefluk@gmail.com>",
    "Kyle Mitofsky <kylemit@gmail.com>",
	"Matt Hargett <plaztiksyke@gmail.com>",
	"Olivier Trepanier <otrepanier@roblox.com>",
]
content_root = "src"
default_alias = "graphql"

[dependencies]
RegExp = "github.com/Roblox/luau-regexp@0.2.0"
LuauPolyfill = "github.com/Roblox/luau-polyfill@0.3.0"
Promise = "github.com/Roblox/roblox-lua-promise@3.2.1"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.3.1"

